GET http://localhost:3000/api/v1/subject
cookie:access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Y2M1NWU4OWY0OTQ2N2QxMjZlOTAzZSIsIm5hbWUiOiJmZWZlIiwiZW1haWwiOiJhaG1lZEBkeGR4c2dtYWlsb2UuY29tIiwiY3JlYXRlZEF0IjoiMjAyNS0wMy0wOFQxNDozNjoyNC4xODNaIiwidXBkYXRlZEF0IjoiMjAyNS0wMy0wOFQxNDozNjoyNC4xODNaIiwiX192IjowLCJpYXQiOjE3NDE1MjA1NzIsImV4cCI6MTc0MTUyNDE3MiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.jjiax7-oFO7mFilzz4uMyoupkM6d8eVVTRZ2eS6PTHA
