GET http://localhost:3000/api/v1/user/profile
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Y2MwZTFhZjBjODIxYTY2MjU0NGQwMyIsIm5hbWUiOiJmZWZlIiwiZW1haWwiOiJzc3N6Znhzc3NzQGR4ZHhzb2UuY29tIiwiY3JlYXRlZEF0IjoiMjAyNS0wMy0wOFQwOTozMDowMi4yNTRaIiwidXBkYXRlZEF0IjoiMjAyNS0wMy0wOFQwOTozMDowMi4yNTRaIiwiX192IjowLCJpYXQiOjE3NDE0Mzc5ODEsImV4cCI6MTc0MTQ0MTU4MSwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.5A7-PjmbH5iVF_J2a4QrJ1oMOJ43XVsK5ZdeNsTph9g

